[theme.light]
primaryColor = "#4f46e5"
backgroundColor = "#fafafa"
secondaryBackgroundColor = "#f1f5f9"
textColor = "#0f172a"

[theme.dark]
primaryColor = "#4139bc"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1b1f2e"
textColor = "#e5e7eb"

font = "sans serif"